ansiblePower.py updated to test unit test
Unit test detect and pipeline failed, logs:

Run python tests/ut_ansiblePower.py
Traceback (most recent call last):
  File "/home/runner/work/AnsiblePower/AnsiblePower/tests/ut_ansiblePower.py", line 9, in <module>
    from ansiblePower import load_config, save_config, load_history, save_history
  File "/home/runner/work/AnsiblePower/AnsiblePower/ansiblePower.py", line 93
    with open dummy(HISTORY_FILE, "r") as f:
              ^
SyntaxError: invalid syntax
Error: Process completed with exit code 1.